services:
  bulksms:
    container_name: bulksms
    restart: always
    build: ./src
    ports:
      - "8080:8080"
    depends_on:
      - bulkdb 
    networks:
      - bulk
    volumes:
      - ./data1:/usr/src/app/assets/images/
      
  bulkdb:
    container_name: bulkdb
    image: mongo:latest
    restart: always
    ports:
      - "27017"
    networks:
      - bulk
    volumes:
      - ./data:/data/db
    command: ["/usr/bin/mongod","--bind_ip_all"]

networks:
  bulk:
    driver: bridge

volumes:
  data:
  data1: